apiVersion: v1
kind: Service
metadata:
  name: {{ template "hello-world-helm.fullname" . }}
  labels:
    app: {{ template "hello-world-helm.name" . }}
    env: {{ .Values.environment.name }}
    chart: {{ template "hello-world-helm.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.name }}
  selector:
    app: {{ template "hello-world-helm.name" . }}
    release: {{ .Release.Name }}
