apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "nginx-helm.fullname" . }}
  labels:
    app: {{ template "nginx-helm.name" . }}
    env: {{ .Values.environment.name }}
spec:
  selector:
    matchLabels:
      app: {{ template "nginx-helm.name" . }}
      env: {{ .Values.environment.name }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "nginx-helm.name" . }}
        env: {{ .Values.environment.name }}
    spec:
      containers:
      - name: {{ template "nginx-helm.name" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80
          name: http