apiVersion: v1
kind: Service
metadata:
  name: {{ template "nginx-helm.fullname" . }}
  labels:
    app: {{ template "nginx-helm.name" . }}
    env: {{ .Values.environment.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.name }}
  selector:
    app: {{ template "nginx-helm.name" . }}
    env: {{ .Values.environment.name }}