# Default values for redis-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

deployment:
  name: redis

image:
  repository: redis
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: redis
  type: ClusterIP
  port: 6379

labels:
  app: redis
  env: testing
  role: master

containers:
  name: master

resources:
  requests:
    cpu: 100m
    memory: 100Mi

nodeSelector: {}

tolerations: []

affinity: {}
