apiVersion: v1
kind: Service
metadata:
  name: php-apache
  labels:
    app: loader-test
    env: testing
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      name: http
  selector:
    app: php-apache
    env: testing