apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
    role: slave
    env: testing
spec:
  ports:
  - port: 6379
  selector:
    app: redis
    role: slave
    env: testing